name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build project (Release)
        run: dotnet publish ./Phos.MusicManager.Desktop -c Release -o ./PhosMusicManager

      - name: Zip folder
        run: Compress-Archive -Path ./PhosMusicManager -DestinationPath ./PhosMusicManager.zip

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ./PhosMusicManager.zip
          fail_on_unmatched_files: true